name: addictedtofloors
favicon: null
layout_spectrum: 0.7795699
typography_spectrum: 0.9392729471437633
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#181b14'
    - '#e38db4'
    - '#d04c7b'
    - '#fafafa'
    - '#56542e'
  brandStrength: 1
  lightness: 0.4375
  saturation: 0.75
  rhythmicContrast: 0.2618781470227987
purpose: []
