analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.7701723368372768
  brandStrength: 1
  lightness: 0.2129061734303832
  brandColors:
    - '#FFFFFF'
    - '#125688'
    - '#25272A'
    - '#A5A7AA'
    - '#FA804B'
  rhythmicContrast: 0.2618781470227987
typography_spectrum: 0.9392729471437633
layout_spectrum: 0.7795699
cta:
  bucket: null
  version: null
  domain: null
favicon: null
name: addictedtofloors
