name: addictedtofloors
favicon: null
layout_spectrum: 0.8787661043461412
typography_spectrum: 0.9392729471437633
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.28020447841845453
  lightness: 0.2129061734303832
  saturation: 0.7701723368372768
  rhythmicContrast: 0.26187814702279866
purpose: []
